helpdesk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('', include(('scheduler.urls'))),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import profile, super_pannel, update_emails, email_settings


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('superadmin/', super_pannel, name='super-panel'),
    path('superadmin/emails', update_emails, name='update-emails'),
    path('superadmin/email-settings', email_settings, name='email-settings'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('profile/', profile, name='user-profile')
]

scheduler/models.py
from django.db import models
from django.utils import timezone
from datetime import date
from users.models import User
from django.urls import reverse


class Skill(models.Model):

    skill_type = models.CharField(max_length=255)
    skilled_staff = models.ManyToManyField(User)

    def __str__(self):
        return self.skill_type


class StaffProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        self.user.username


class Department(models.Model):

    department_name = models.CharField(max_length=50)

    def __str__(self):
        return self.department_name


class Priority(models.Model):

    priority = models.CharField(max_length=50)

    def __str__(self):
        return self.priority


class Status(models.Model):

    status = models.CharField(max_length=50)

    def __str__(self):
        return self.status


class Ticket(models.Model):

    subject = models.CharField(max_length=255)
    username = models.CharField("Your Name", max_length=255)
    email = models.EmailField(max_length=255)
    user_department = models.ForeignKey(Department, on_delete=models.CASCADE)
    request_type = models.ForeignKey(Skill, on_delete=models.CASCADE)
    location_info = models.TextField(blank=True, null=True)
    ticket_priority = models.ForeignKey(Priority, on_delete=models.CASCADE, default=1)
    ticket_status = models.ForeignKey(Status, on_delete=models.CASCADE, default=1)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    date_due = models.DateTimeField(blank=True, null=True)
    ticket_description = models.TextField()
    staff_assigned = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.subject} ({self.user_department}) ({self.username})'

    def get_absolute_url(self):
        return reverse('ticket-detail', kwargs={'pk':self.pk})

    @property
    def is_due_date(self):
        return date.today() == self.date_due


class Note(models.Model):

    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    staff_user = models.ForeignKey(User, on_delete=models.CASCADE)
    ticket_note = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.ticket} {self.staff_user} \n {self.date_created}'


class ToDo(models.Model):

    staff_user = models.ForeignKey(User, on_delete=models.CASCADE)
    todo_name = models.CharField(max_length=255)
    todo = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.todo}'


class Notification(models.Model):

    notification = models.CharField(max_length=255)

    def __str__(self):
        return self.notification


class KnowledgeBase(models.Model):

    question = models.TextField()
    answer = models.TextField()

    def __str__(self):
        return self.question


class EmailCreds(models.Model):

    email = models.EmailField(max_length=255)
    smtp_server = models.CharField(max_length=255)
    port = models.CharField(max_length=50)
    password = models.CharField(max_length=255)

    def __str__(self):
        return self.email


class Email(models.Model):

    email_name = models.CharField(max_length=255)
    subject = models.CharField(max_length=255)
    body = models.TextField()

    def __str__(self):
        return self.email_name




    

users/models.py
from django.db import models
from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser, BaseUserManager


class LoggedUser(models.Model):

    name = models.CharField(max_length=30)
    email = models.EmailField(primary_key=True)
    last_login = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.email

    def login_user(sender, request, user, **kwargs):
        logged_in_users = LoggedUser.objects.filter(email=user.email)
        if not logged_in_users:
            LoggedUser(name=str(user.first_name + " " + " " + user.last_name), email=user.email).save()

    def logout_user(sender, request, user, **kwargs):
        try:
            u = LoggedUser.objects.get(pk=user.email)
            u.delete()
        except LoggedUser.DoesNotExist:
            pass

    user_logged_in.connect(login_user)
    user_logged_out.connect(logout_user)

class UserManager(BaseUserManager):

    def create_user(self, email, first_name, middle_name, last_name, password=None, **extra_fields):
        if not email:
            raise ValueError("User must have an email address")
        if not password:
            raise ValueError("Please provide a password for authentication")
        if not first_name:
            raise ValueError("First name is required")
        if not last_name:
            raise ValueError("Last name is required")
        email = self.normalize_email(email)
        user_obj = self.model(
            email=email, **extra_fields
        )

        user_obj.set_password(password)
        user_obj.first_name = first_name
        user_obj.middle_name = middle_name
        user_obj.last_name = last_name
        # user_obj.is_staff = is_staff
        # user_obj.is_admin = is_admin
        # user_obj.is_active = is_active
        user_obj.save(using=self._db)
        return user_obj

    # def create_staffuser(self, email, first_name, middle_name, last_name, password=None):
    #     user = self.create_user(
    #         email,
    #         first_name,
    #         middle_name,
    #         last_name,
    #         password = password,
    #         is_staff = True
    #     )
    #     return user

    def create_superuser(self, email, first_name, middle_name, last_name, password=None, **extra_fields):

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)


        user = self.create_user(
            email,
            first_name,
            middle_name,
            last_name,
            password = password,
            **extra_fields
        )
        print(user.is_superuser)
        return user


class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)  # is the account active or not
    is_staff = models.BooleanField(default=True)   # is a staff or an admin
    # is_admin = models.BooleanField(default=False)  # is a superuser/admin

    USERNAME_FIELD = 'email'  # username and password are required by default

    REQUIRED_FIELDS = ['first_name', 'middle_name', 'last_name']

    objects = UserManager()

    def __str__(self):
        return "{} {} {}".format(self.first_name, self.middle_name, self.last_name)

    def get_email(self):
        return self.email

    # def has_perm(self, perm, obj=None):
    #     return True
    #
    # def has_module_perms(self, app_label):
    #     return True

    # @property
    # def is_staff(self):
    #     return self.staff
    #
    # @property
    # def is_admin(self):
    #     return self.admin
    #
    # @property
    # def is_active(self):
    #     return self.active

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from scheduler.models import Department, Skill


User = get_user_model()


class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""

    is_staff = forms.BooleanField(label="Staff Status")
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    # first_name = forms.CharField(label='First Name')
    # middle_name = forms.CharField(label='Middle Name')
    # last_name = forms.CharField(label='Last Name')

    class Meta:
        model = User
        fields = ('first_name', 'middle_name', 'last_name', 'email', 'is_staff', 'is_superuser')  # 'full_name',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password',)

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class DepartmentForm(forms.ModelForm):

    department_name = forms.CharField(label='Department Name')

    class Meta:
        model = Department
        fields = ('department_name',)


class SkillForm(forms.ModelForm):

    skill_type = forms.CharField(label='Skill Name', max_length=30)
    # skilled_staff = forms.ChoiceField()

    class Meta:
        model = Skill
        fields = ('skill_type', 'skilled_staff',)


class SkillUpdateForm(forms.ModelForm):

    class Meta:
        model = Skill
        fields = ('skilled_staff',)

users/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib import messages

from django.http import JsonResponse

import logging
from ipware import get_client_ip

# Models Import
from scheduler.models import Ticket, Department, Skill, ToDo, Email, EmailCreds

# Forms Import
from .forms import UserAdminCreationForm, DepartmentForm, SkillForm, SkillUpdateForm


# Handling Logging

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

formatter = logging.Formatter('%(message)s:%(asctime)s')

file_handler = logging.FileHandler('./logs/admin.log')
file_handler.setFormatter(formatter)

logger.addHandler(file_handler)

# ###################################### #

@login_required(login_url = '/')
def profile(request):

    User = get_user_model().objects.get(id=request.user.id)

    tickets = Ticket.objects.filter(staff_assigned = User)
    notes = ToDo.objects.filter(staff_user = User)

    context = {
        'tickets': tickets,
        'notes': notes,
        'title': 'Technician Profile'
    }

    return render(request, 'users/profile.html', context)

# Handling Super User Forms and Panel

def super_pannel(request):

    context = {}
    users = get_user_model().objects.all()
    skills = Skill.objects.all()
    departments = Department.objects.all()
    tickets = Ticket.objects.filter(is_deleted=False)
    new_email = Email.objects.get(id=1)
    update_email = Email.objects.get(id=2)
    close_email = Email.objects.get(id=3)
    email_settings = EmailCreds.objects.first()

    client_ip = get_client_ip(request)

    if request.method == 'POST':

        # print (request.POST)

        Userform = UserAdminCreationForm(request.POST)
        Departform = DepartmentForm(request.POST)
        SkForm = SkillForm(request.POST)
        SKUpdateForm = SkillUpdateForm(request.POST)

        context = {
            'title': 'Super Admin Panel',
            'users': users,
            'tickets': tickets,
            'skills': skills,
            'departments': departments,
            'new_email': new_email,
            'update_email': update_email,
            'close_email': close_email,
            'Userform': Userform,
            'DepartForm': Departform,
            'SkillForm': SkForm,
            'SkillUForm': SKUpdateForm,
            'emailSettings': email_settings,
        }

        if Userform.is_valid():
            Userform.save()
            email = Userform.cleaned_data.get('email')
            logger.info(f'New Technician [{email}] has been added by [{request.user.first_name} {request.user.middle_name} {request.user.last_name}] IP {client_ip}')
            messages.success(request, f'New user has been created they will be able to log in')
            return render(request, 'users/admin.html', context)

        if Departform.is_valid():
            Departform.save()
            departname = Departform.cleaned_data.get('department_name')
            logger.info(
                f'New Department [{departname}] has been added by [{request.user.first_name} {request.user.middle_name} {request.user.last_name}] IP {client_ip}')
            messages.success(request, f'New Department has been added')
            return render(request, 'users/admin.html', context)

        if SkForm.is_valid():
            SkForm.save()
            skilname = SkForm.cleaned_data.get('skill_type')
            logger.info(
                f'New Skill [{skilname}] has been added by [{request.user.first_name} {request.user.middle_name} {request.user.last_name}] IP {client_ip}')
            messages.success(request, f'New Skill has been added')
            context['SkillForm'] = SkillForm()
            context['SkillUForm'] = SkillUpdateForm()
            return render(request, 'users/admin.html', context)

        if SKUpdateForm.is_valid():
            skill = Skill.objects.get(id=request.POST.get('skillID'))
            skilled_staff_list = request.POST.getlist('skilled_staff')

            for user in skilled_staff_list:
                u = users.get(id=user)
                skill.skilled_staff.add(u)

            skill.save()
            context['SkillUForm'] = SkillUpdateForm()
            return render(request, 'users/admin.html', context)

        # If any admin form is not valid

        elif not Userform.is_valid():
            return render(request, 'users/admin.html', context)
        elif not Departform.is_valid():
            return render(request, 'users/admin.html', context)
        elif not SkForm.is_valid():
            return render(request, 'users/admin.html', context)

    else:

        Userform = UserAdminCreationForm()
        Departform = DepartmentForm()
        SkForm = SkillForm()
        SKUpdateForm = SkillUpdateForm()

        context = {
            'title': 'Super Admin Panel',
            'users': users,
            'tickets': tickets,
            'skills': skills,
            'departments': departments,
            'new_email': new_email,
            'update_email': update_email,
            'close_email': close_email,
            'Userform': Userform,
            'DepartForm': Departform,
            'SkillForm': SkForm,
            'SkillUForm': SkillUpdateForm,
            'emailSettings': email_settings,
        }

        return render(request, 'users/admin.html', context)

# ############################# #

# Ajax handling Email Forms

def update_emails(request):

    email_id = request.GET.get("id")
    email = Email.objects.get(id=email_id)
    email.subject = request.GET.get("subject")
    email.body = request.GET.get("body")
    email.save()

    return JsonResponse({"success": f'{email.email_name} has been updated'})

def email_settings(request):

    email_setting = EmailCreds.objects.first()
    email_setting.email = request.GET.get("email")
    email_setting.smtp_server = request.GET.get("smtp")
    email_setting.port = request.GET.get("port")
    email_setting.password = request.GET.get("password")
    email_setting.save()

    return JsonResponse({"success": "Settings have been updated."})

users/templates/users/login.html
{% extends 'scheduler/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">
            <button type="submit" class="btn btn-danger">Sign Up</button>
        </div>
    </form>


{% endblock content %}

users/templates/users/profile.html
{% extends 'scheduler/base.html' %}

{% block content %}

<div style="display: none" class="alert alert-success"></div>

<div class="row">
    <div class="col">
        <div class="border border-danger">
            <div class="bg-danger text-white pl-3 pt-2 pb-1">
                <h4 class="d-inline-block">Profile Info</h4>
                <span class="fas fa-minus icon-float-r" data-toggle="collapse" data-target="#widget-1"></span>
            </div>
            <div id="widget-1" class="profile-widget py-3 px-2 collapse show">
                <!--                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>-->
                <div class="row justify-content-center text-center">
                    <div class="col border-right border-danger">
                        <p class="profile-widget--text">{{request.user.first_name}} {{request.user.middle_name}}
                            {{request.user.last_name}}</p> <br>
                        <p><i class="profile-icon fas fa-user-tie"></i></p>
                    </div>
                    <div class="col border-right border-danger">
                        <p class="profile-widget--text">{{request.user.email}}</p> <br>
                        <p><i class="profile-icon fas fa-envelope-open-text"></i></p>
                    </div>
                    <div class="col border-right border-danger">
                        <p class="profile-widget--text">{{request.user.ticket_set.count}} Tickets Assigned</p> <br>
                        <p><i class="profile-icon fas fa-ticket-alt"></i></p>
                    </div>
                    <div class="col">
                        <p class="profile-widget--text">4 Tickets</p> <br>
                        <p><i class="profile-icon fas fa-ticket-alt"></i></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row">

    <div class="col-md-8">

        <div class="container my-5">

            <div class="heading-primary mb-5">
                <p class="heading-primary--text">Tickets Assigned</p>
            </div>

            <table class="table table-bordered table-stripped my-5">
                <thead class="bg-danger">
                <tr>
                    <th>Subject</th>
                    <th>Request By</th>
                    <th>Status</th>
                    <th>Priority</th>
                </tr>
                </thead>
                <tbody>

                {% for ticket in tickets %}
                <tr>
                    <td><a href="{% url 'ticket-detail' ticket.id %}">{{ticket.subject}}</a></td>
                    <td>{{ticket.username}}</td>
                    <td>{{ticket.ticket_status}}</td>
                    <td>{{ticket.ticket_priority}}</td>
                </tr>
                {% endfor %}

                </tbody>
            </table>

        </div>

        <form id="todo-form" style="display: none;">
            <fieldset>
                <legend>New Todo:</legend>
                <input type="hidden" value="{{request.user.id}}" name="user_id" id="input_id">
                <div class="form-group">
                    <label for="subject">Subject</label>
                    <input id="subject" name="subject" class="form-control" placeholder="Subject Here">
                </div>
                <div class="form-group">
                    <label for="body">Body</label>
                    <textarea id="body" name="body" cols="30" rows="10" class="form-control"></textarea>
                </div>
                <button type="submit" id="todo-button" class="btn btn-danger">Add ToDo</button>
            </fieldset>
        </form>

    </div>

    <div class="col-md-4">

        <div class="container my-5">

            <div class="heading-primary mb-5">
                <p class="heading-primary--text">ToDo/Notes</p>
                <span id="add-todo" class="heading-primary--icon"><i class="fas fa-plus-square"></i></span>
            </div>

            <div class="todo list-group">

                {% for todo in notes %}

                <a href="#" class="list-group-item list-group-item-action flex-column align-items-start start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{todo.todo_name}} <i data-noteId="{{todo.id}}" class="delete-note fas fa-trash-alt"></i></h5>
                        <small>{{todo.date_created}}</small>
                    </div>
                    <p class="mb-1">{{todo.todo}}</p>
                </a>

                {% endfor %}
            </div>
        </div>

    </div>
</div>


{% endblock content %}

{% block js %}


<script>

    $(document).ready(function () {

        function alertTimeOut(alertId) {
            window.setTimeout(function () {
                $(alertId).fadeTo(2000, 0).slideUp(2000, function () {
                    $(this).remove();
                })
            }, 2000);
        };

        let alert = $('.alert').hide()


        const addTodo = $('#add-todo');

        addTodo.on('click', function (event) {
            $('#todo-form').show()
        })

        $('#todo-button').on('click', function (event) {


            var fromdata = $('#todo-form').serialize()


            $.ajax({

                request: 'POST',
                url: "{% url 'create-todo' %}",
                data: fromdata,
                dataType: 'json'

            }).done(function (data) {

                $('#todo-form').hide()

            })
        });

        $('.todo').on('click', '.delete-note', function (event) {
            let currentTarget = $(event.currentTarget);
            let targetRow = currentTarget.closest('a');
            console.log(targetRow)
            bootbox.confirm("Are you sure?", function(result){
                if (result) {
                    let todoId = currentTarget.attr('data-noteId');
                    console.log(todoId)
                    $.ajax({
                        url: "{% url 'delete-todo' %}",
                        data: {'todo_id': todoId },
                        dataType: 'json'
                    }).done(function (data) {
                        if (data['success']) {
                            alert.show()
                            alert.text(data['success'])
                            alertTimeOut(alert)
                            targetRow.remove();
                        }
                    })
                }
            })
        })


    });

</script>


{% endblock js %}